# Generated by Django 6.0.1 on 2026-01-09 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
