# Generated by Django 6.0.1 on 2026-01-11 19:26

import django_mongodb_backend.fields
import llama_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llama_api', '0002_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], default='USER', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model=llama_api.models.Message),
        ),
    ]
